- hosts: localhost
  pre_tasks:
          - name: Update APT
            become: true
            apt:
                    force_apt_get: true
                    update_cache: true
                    state: present
  tasks:
          - name: Install dependency packages
            apt:
                name: ["ninja-build", "gettext", "libtool", "libtool-bin", "autoconf", "automake", "cmake", "g++", "pkg-config", "unzip", "curl", "doxygen", "stow", "git"]
            become: true
            tags:
                    - neovim
                    - dotfiles

          - name: Prepare directory ~/Code/OSS
            ansible.builtin.file:
                    path: ~/Code/OSS
                    recurse: true
                    state: directory
                    mode: '0755'
            tags:
                    - neovim
                    - dotfiles
          - name: Prepare directory ~/Code/Work
            ansible.builtin.file:
                    path: ~/Code/Work
                    recurse: true
                    state: directory
                    mode: '0755'
            tags:
                    - neovim
                    - dotfiles

          - name: Clone Dotfiles
            ansible.builtin.git: 
                repo: 'https://github.com/primalivet/dotfiles.git'
                dest: ~/Code/OSS/dotfiles
                force: true
          - name: Set Tmux config
            shell: cd ~/Code/OSS/dotfiles && stow tmux --no-folding -t ~
            tags: 
                - dotfiles
                - tmux
          - name: Set Neovim config
            shell: cd ~/Code/OSS/dotfiles && stow nvim --no-folding -t ~
            tags: 
                - dotfiles
                - neovim

          - name: Install Tmux
            become: true
            apt:
                    name: tmux
            tags: 
                - tmux

          - name: Clone FZF
            ansible.builtin.git:
                    repo: https://github.com/junegunn/fzf.git
                    dest: ~/.fzf
            tags: 
                - fzf
                - neovim
          - name: Install FZF
            become: true
            shell: "{{ lookup('env', 'HOME') }}/.fzf/install --all"
            tags: 
                - fzf
                - neovim

          - name: Remove Neovim
            ansible.builtin.file:
                    path: ~/neovim
                    state: absent
            tags:
                    - neovim
          - name: Clone Neovim
            ansible.builtin.git:
                repo: 'https://github.com/neovim/neovim.git'
                dest: ~/neovim
            tags:
                - neovim
          - name: Build Neovim
            shell: cd ~/neovim && make -j 20
            tags:
                - neovim
          - name: Install Neovim
            become: true
            shell: cd ~/neovim && make install
            tags:
                - neovim
          - name: Install Neovim package manager, Packer
            ansible.builtin.git:
                repo: 'https://github.com/wbthomason/packer.nvim'
                dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
            tags: 
                - neovim
